name: Generate Documentation

on:
  pull_request:
    types: [closed]
    paths:
      - 'src/**'

jobs:
  build:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai

    - name: Generate Documentation
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python generate_documentation.py

    - name: Setup SSH
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Commit and Push Documentation
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        if git status --porcelain | grep 'docs/'; then
          git add docs/
          git commit -m "Update documentation"
          git push git@github.com:igorgorbenko/gpt_doc_generator.git dev
        else
          echo "No changes to commit."
        fi
